CIRCLE_BUILD_NUM added in the final build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,9 +14,6 @@ jobs:
     # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
     docker:
       - image: cimg/node:16.10
-    environment:
-      GIT_COMMIT_MSG: ${git log --format=oneline -n 1 $CIRCLE_SHA1}
-      GIT_SHA1_SHORT: ${CIRCLE_SHA1:0:7}
     steps:
       # Checkout the code as the first step.
         - checkout
@@ -30,54 +27,52 @@ jobs:
             command: |
               touch .env
               echo "VUE_APP_ENV=production /n VUE_APP_NETWORK=$APP_NETWORK_CELO" > .env
-              echo $GIT_COMMIT_MSG
-              echo $GIT_SHA1_SHORT
-        # - run:
-        #     name: Setting appspec
-        #     command: |
-        #       touch appspec.yml
-        #       echo "version: 0.0
-        #       os: windows
-        #       files:
-        #         - source: .
-        #           destination: C:\inetpub\Symmetric\uat\celo\Pools.UI" > appspec.yml      
-        # - run:
-        #     name: Run Build
-        #     command: npm run build
-        # - run:
-        #     name: Compress Artifacts
-        #     command: zip -qr $CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_CELO.zip ./dist appspec.yml
-        # - aws-s3/copy:
-        #     from: $CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_CELO.zip 
-        #     to: $AWS_BUCKET_LOCATION 
-        # - run:    
-        #     name: Iniitate Code-Deploy
-        #     command: |
-        #       ID=$(aws deploy create-deployment \
-        #             --application-name $APP_NAME \
-        #             --deployment-config-name CodeDeployDefault.AllAtOnce \
-        #             --deployment-group-name $DEPLOYMENT_GROUP \
-        #             --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=uat/$CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_CELO.zip \
-        #             --description "$GIT_COMMIT_MSG" \
-        #             --output text \
-        #             --query 'deploymentId')
-        #       echo $ID      
-        #       STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
-        #       echo "STATUS: $STATUS..."
-        #       while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
-        #               echo "Status: $STATUS..."
-        #               STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
-        #               sleep 5
-        #             done
-        #             if [[ $STATUS == "Succeeded" ]]; then
-        #               EXITCODE=0
-        #               echo "Deployment finished."
-        #             else
-        #               EXITCODE=1
-        #               echo "Deployment failed!"
-        #             fi
-        #             aws deploy get-deployment --deployment-id $ID
-        #             exit $EXITCODE
+        - run:
+            name: Setting appspec
+            command: |
+              touch appspec.yml
+              echo "version: 0.0
+              os: windows
+              files:
+                - source: .
+                  destination: C:\inetpub\Symmetric\uat\celo\Pools.UI" > appspec.yml      
+        - run:
+            name: Run Build
+            command: npm run build
+        - run:
+            name: Compress Artifacts
+            command: zip -qr $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO.zip ./dist appspec.yml
+        - aws-s3/copy:
+            from: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO.zip 
+            to: $AWS_BUCKET_LOCATION 
+        - run:    
+            name: Iniitate Code-Deploy
+            command: |
+              ID=$(aws deploy create-deployment \
+                    --application-name $APP_NAME \
+                    --deployment-config-name CodeDeployDefault.AllAtOnce \
+                    --deployment-group-name $DEPLOYMENT_GROUP \
+                    --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=uat/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO.zip \
+                    --description "$GIT_COMMIT_MSG" \
+                    --output text \
+                    --query 'deploymentId')
+              echo $ID      
+              STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
+              echo "STATUS: $STATUS..."
+              while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
+                      echo "Status: $STATUS..."
+                      STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
+                      sleep 5
+                    done
+                    if [[ $STATUS == "Succeeded" ]]; then
+                      EXITCODE=0
+                      echo "Deployment finished."
+                    else
+                      EXITCODE=1
+                      echo "Deployment failed!"
+                    fi
+                    aws deploy get-deployment --deployment-id $ID
+                    exit $EXITCODE
 
   build-and-deploy-xdai:
     # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
@@ -85,9 +80,6 @@ jobs:
     # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
     docker:
       - image: cimg/node:16.10
-    environment:
-      GIT_COMMIT_MSG: ${echo git log --format=oneline -n 1 $CIRCLE_SHA1}
-      GIT_SHA1_SHORT: ${echo CIRCLE_SHA1:0:7}
     steps:
       # Checkout the code as the first step.
         - checkout
@@ -115,9 +107,9 @@ jobs:
             command: npm run build
         - run:
             name: Compress Artifacts
-            command: zip -qr $CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_XDAI.zip ./dist appspec.yml
+            command: zip -qr $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_XDAI.zip ./dist appspec.yml
         - aws-s3/copy:
-            from: $CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_XDAI.zip
+            from: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_XDAI.zip
             to: $AWS_BUCKET_LOCATION 
         - run:    
             name: Iniitate Code-Deploy
@@ -126,7 +118,7 @@ jobs:
                     --application-name $APP_NAME \
                     --deployment-config-name CodeDeployDefault.AllAtOnce \
                     --deployment-group-name $DEPLOYMENT_GROUP \
-                    --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=uat/$CIRCLE_BRANCH-$GIT_SHA1_SHORT-$APP_NETWORK_XDAI.zip \
+                    --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=uat/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_XDAI.zip \
                     --description "$GIT_COMMIT_MSG" \
                     --output text \
                     --query 'deploymentId')
@@ -156,7 +148,7 @@ workflows:
   Build-and-Deploy:
     jobs:
       - build-and-deploy-celo
-      # - build-and-deploy-xdai:
-      #     requires:
-      #      - build-and-deploy-celo
+      - build-and-deploy-xdai:
+          requires:
+           - build-and-deploy-celo
 
